language: php
php:
  - '5.6'

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml tests
  - phpunit tests/BoletoTest.php
  - phpunit tests/TarjetitaTest.php
  - phpunit tests/transbordoTest.php

after_script:
  - php vendor/bin/coveralls -v
  
notifications:
  email: false
